=== kimipsen/Groupify/.nuke/build.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "$ref": "#/definitions/build",
  "title": "Build Schema",
  "definitions": {
    "build": {
      "type": "object",
      "properties": {
        "ArtifactsType": {
          "type": "string",
          "description": "Artifacts Type"
        },
        "Configuration": {
          "type": "string",
          "description": "Configuration to build - Default is 'Debug' (local) or 'Release' (server)",
          "enum": [
            "Debug",
            "Release"
          ]
        },
        "Continue": {
          "type": "boolean",
          "description": "Indicates to continue a previously failed build attempt"
        },
        "Copyright": {
          "type": "string",
          "description": "Nuget package copyright"
        },
        "ExcludedArtifactsType": {
          "type": "string",
          "description": "Excluded Artifacts Type"
        },
        "GitHubUser": {
          "type": "string"
        },
        "Help": {
          "type": "boolean",
          "description": "Shows the help text for this build assembly"
        },
        "Host": {
          "type": "string",
          "description": "Host for execution. Default is 'automatic'",
          "enum": [
            "AppVeyor",
            "AzurePipelines",
            "Bamboo",
            "Bitbucket",
            "Bitrise",
            "GitHubActions",
            "GitLab",
            "Jenkins",
            "Rider",
            "SpaceAutomation",
            "TeamCity",
            "Terminal",
            "TravisCI",
            "VisualStudio",
            "VSCode"
          ]
        },
        "MyGetApiKey": {
          "type": "string",
          "description": "MyGet Api Key",
          "default": "Secrets must be entered via 'nuke :secrets [profile]'"
        },
        "MyGetNugetFeed": {
          "type": "string",
          "description": "MyGet Feed Url for Public Access of Pre Releases"
        },
        "NoLogo": {
          "type": "boolean",
          "description": "Disables displaying the NUKE logo"
        },
        "NugetApiKey": {
          "type": "string",
          "description": "Nuget Api Key",
          "default": "Secrets must be entered via 'nuke :secrets [profile]'"
        },
        "NugetDescription": {
          "type": "string",
          "description": "Nuget package description"
        },
        "NugetFeed": {
          "type": "string",
          "description": "Nuget Feed Url for Public Access of Releases"
        },
        "Partition": {
          "type": "string",
          "description": "Partition to use on CI"
        },
        "Plan": {
          "type": "boolean",
          "description": "Shows the execution plan (HTML)"
        },
        "Profile": {
          "type": "array",
          "description": "Defines the profiles to load",
          "items": {
            "type": "string"
          }
        },
        "Root": {
          "type": "string",
          "description": "Root directory during build execution"
        },
        "Skip": {
          "type": "array",
          "description": "List of targets to be skipped. Empty list skips all dependencies",
          "items": {
            "type": "string",
            "enum": [
              "Clean",
              "Compile",
              "MutationTests",
              "Pack",
              "PushGithub",
              "PushMyget",
              "PushNugetOrg",
              "Release",
              "Restore",
              "Test"
            ]
          }
        },
        "Solution": {
          "type": "string",
          "description": "Path to a solution file that is automatically loaded"
        },
        "Target": {
          "type": "array",
          "description": "List of targets to be invoked. Default is '{default_target}'",
          "items": {
            "type": "string",
            "enum": [
              "Clean",
              "Compile",
              "MutationTests",
              "Pack",
              "PushGithub",
              "PushMyget",
              "PushNugetOrg",
              "Release",
              "Restore",
              "Test"
            ]
          }
        },
        "Verbosity": {
          "type": "string",
          "description": "Logging verbosity during build execution. Default is 'Normal'",
          "enum": [
            "Minimal",
            "Normal",
            "Quiet",
            "Verbose"
          ]
        }
      }
    }
  }
}

=== kimipsen/Groupify/.nuke/parameters.json
{
  "$schema": "./build.schema.json",
  "Solution": "Groupify.sln",
  "ArtifactsType": "*.nupkg",
  "ExcludedArtifactsType": "symbols.nupkg",
  "MyGetNugetFeed": "https://www.myget.org/F/groupify/api/v3/index.json",
  "NugetFeed": "https://api.nuget.org/v3/index.json",
  "NugetDescription": "",
  "Copyright": "Â©Kim Ipsen 2024"
}
